[package]
name = "rusty-bot"
version = "0.1.0"
authors = ["Noah Brabec <noah.brabec@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scrap = "0.5.0"
repng = "0.2.2"
chrono = "0.4.11"
